# Generated by Django 3.2.15 on 2022-10-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_orders_delivered_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expected_delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
